version: 0.1 ({build})
skip_branch_with_pr: true

image:
- Visual Studio 2019

init:
  - call make

platform:
- x64

configuration:
- Release

clone_folder: C:\Hazel

before_build:
  - cd C:\Hazel\CI_test\scripts
  - Win-GenProjects.bat

build:
  project: C:\Hazel\CI_test\Hazel.sln
  parallel: true
  verbosity: normal
