version: 0.1 ({build})
skip_branch_with_pr: true

image:
- Visual Studio 2019

init:
  - set makefiles="MinGW Makefiles"

platform:
- x64

configuration:
- Release

clone_folder: C:\Hazel

build:
  project: C:\Hazel
  parallel: true
  verbosity: normal
